package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.ProjectFeature
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        val feature1 = find<ProjectFeature> {
            feature {
                type = "IssueTracker"
                id = "PROJECT_EXT_17"
                param("name", "gl-sb")
                param("repository", "https://gitlab.com/manturovDan/sandbox1")
                param("secure:accessToken", "credentialsJSON:3c0103f2-e0e8-4326-8297-561ac3fe60a1")
                param("type", "GitLabIssues")
            }
        }
        feature1.apply {
        }
        val feature2 = find<ProjectFeature> {
            feature {
                type = "IssueTracker"
                id = "PROJECT_EXT_5"
                param("authType", "anonymous")
                param("name", "gl-anon")
                param("repository", "")
                param("secure:accessToken", "")
                param("type", "GitLabIssues")
            }
        }
        feature2.apply {
        }
        add {
            feature {
                type = "IssueTracker"
                id = "PROJECT_EXT_10"
                param("secure:password", "")
                param("name", "gh1")
                param("authType", "accesstoken")
                param("repository", "https://github.com/manturovDan/delay")
                param("type", "GithubIssues")
                param("secure:accessToken", "credentialsJSON:83896ea8-0aba-4dcb-8e31-6ef6b2224b0e")
                param("username", "")
            }
        }
    }
}
