package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.ProjectFeature
import jetbrains.buildServer.configs.kotlin.projectFeatures.gitlabConnection
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        val feature1 = find<ProjectFeature> {
            feature {
                type = "IssueTracker"
                id = "PROJECT_EXT_17"
                param("name", "gl-sb")
                param("repository", "https://gitlab.com/manturovDan/sandbox1")
                param("secure:accessToken", "credentialsJSON:3c0103f2-e0e8-4326-8297-561ac3fe60a1")
                param("type", "GitLabIssues")
            }
        }
        feature1.apply {
        }
        val feature2 = find<ProjectFeature> {
            feature {
                type = "IssueTracker"
                id = "PROJECT_EXT_5"
                param("authType", "anonymous")
                param("name", "gl-anon")
                param("repository", "")
                param("secure:accessToken", "")
                param("type", "GitLabIssues")
            }
        }
        feature2.apply {
        }
        add {
            gitlabConnection {
                id = "PROJECT_EXT_23"
                displayName = "GitLab.com"
                applicationId = "f5d7d5b61b637413da3c76ff88968938066e9a78cf4bf2a880dc16bbe4141a09"
                clientSecret = "credentialsJSON:afc6c530-c9c8-487f-9c22-994fb26d39bf"
            }
        }
    }
}
